### PR TITLE
Hiring updates

### PR DESCRIPTION
**Pull request by dannychapman**
Please review @greggersh or @paulsmith 

- Broke out each open position into a stand alone page
- Preserved anchor links on hiring page so nothing breaks
- Updated menu title for We’re hiring
- Improved design bits for job pages

### CODE REVIEW

**Comment by greggersh** [comment]
I took a look at this; I think we need a CTA on each job page. There's no where for the user to go next from that page.

**Comment by dannychapman** [comment]
@greggersh that's a good point. We could make the homework / get in touch really punched up as buttons perhaps.

**Comment by dannychapman** [comment]
@greggersh revised CTA added. Please review!

**Comment by greggersh** [comment]
:+1:

**Pull request merged**
