### PR TITLE
updated min-height on cards

### PR DESCRIPTION
**Pull request by dannychapman**
Made bio cards equal height

### CODE REVIEW

**Comment by dannychapman** [comment]
Completes #76

**Comment by carlmjohnson** [comment]
Can we use flex box for this somehow?

**Comment by dannychapman** [comment]
I haven't had much luck getting Foundation's block grids to play nice with flex box sadly.

**Comment by dannychapman** [comment]
@carlmjohnson hmmm looks like we should make it a task to upgrade to Foundation 6, then use the updated block grids for flex box. 5 Will not play nice.

**Comment by greggersh** [comment]
@dannychapman what's there for me or paul to do?

**Comment by dannychapman** [comment]
@greggersh run locally if you want to take for a spin, otherwise I can just merge.

**Comment by greggersh** [comment]
👍

**Pull request merged**
