### PR TITLE
Add job application link for Product Development Specialist to website

### PR DESCRIPTION
**Pull request by neelbauer1**
We need to send applicants through the job app in Workable, using this link, so I added it to the Ad Hoc Join page:
https://adhocteam.workable.com/jobs/323444

### CODE REVIEW

**Comment by neelbauer1** [comment]
I've randomly tagged great folks to take a look at my cut-and-paste linking job. Rock and roll.

**Comment by llimllib** [comment]
This commit LGTM. Why is waffle spelled `(waffle)` in the job ad? Do we want to list it as a requirement? I wouldn't want to scare somebody off because they hadn't used it before?

**Comment by llimllib** [comment]
Also "manages resources" isn't a sensible "requirement"?

**Comment by dannychapman** [comment]
@llimllib Agreed re: content changes. @neelbauer1 Mind adding me to the job in Workable / making those edits?

**Pull request merged**
